# site settings
title: Jonas Vestergaard 
subtitle: Jensen
email: jvestergaardjensen@gmail.com
description: CV and project portifolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Jonas Vestergaard Jensen
street_address: Jægersborggade 29
city: København N
state: 
zip_code: 2200
country: Denmark
phone: +45 60132195

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/jonasvj
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/jonas-vestergaard-j-b8b5b3156/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

# For cv
style: kjhealy

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
